### PR TITLE
How to access your boxbox from the browser

### PR DESCRIPTION
**Pull request by shiroyasha**

### CODE REVIEW

**Comment by milica-nerlovic** [comment]
:+1:

**Comment by nikolalsvk** [comment]
Or, for instance, in the Rails 5 apps, you have to do `bin/rails server -b 0.0.0.0` to see it at `boxbox:3000`

**Review by bmarkons — APPROVED** [review]
Cool. I prefer using `boxbox:<port>` :)

**Comment by shiroyasha** [comment]
@nikolalsvk Added the info about the 0.0.0.0 interface.
@vonum incorporated the note from the previous PR and and removed `Then`.

**Comment by bmarkons** [comment]
@shiroyasha please provide Developers with access on boxbox repo :)

**Comment by shiroyasha** [comment]
@bmarkons done.

**Pull request merged**
